config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  resources :charities, only: [:index, :show] do
    resources :payments, only: [:new, :create]
    post "favorite", to: "charities#favorite", as: :favorite
    post "dislike", to: "charities#dislike", as: :dislike
    resources :donations, only: [:new ]
  end
  resources :bookmarks, only: [:update, :destroy]
  resources :donations, only: [ :index ]
  resources :user_categories, only: [:update]

  get '/preferences', to: 'categories#index', as: :preferences
  get '/search', to: 'charities#search', as: 'search'
  get '/favorites', to: 'charities#user_charities_index', as: :favorites
end

app/views/shared/_filters.html.erb
<div id="sidebar">
  <div id="filters-close" onclick="toggleSidebar(event, this)"><%= image_tag "close.svg", class: 'icon_close', height: '20', width: '20' %></div>
  <ul>
    <% @categories.each do |category| %>
      <li id="charity_category_names_<%= category.name %>" class="<%= category.name %>" onclick="handleEvent(event, this)">
        <div class="category-info">
          <div class="icon_cat" style="height: 25px ; width:24px; background-repeat: no-repeat; margin:auto;background-image: url('<%= image_path "#{category.name}.svg" %>');">
          </div>
          <p><%= category.pretty_name %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<%= content_for(:after_js) do %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div id="burger-menu">
  <div class="btn_close" onclick="toggleMenu(event, this)">
    <%= image_tag "close.svg", height: '20', width: '20' %>
  </div>
  <% if user_signed_in? %>
    <div class="user-container">
      <div class="avatar-menu">
        <% if current_user.photo? %>
          <%= cl_image_tag current_user.photo.url(:bright_face) %>
        <% else %>
          <%= image_tag("default_avatar.png") %>
        <% end %>
      </div>
      <div class="user-name">
        <h2><%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path %></h2>
      </div>
    </div>
    <div>
      <ul >
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i><%= t(".personal_information", default: "Personal Information") %>
          <% end %>
        </li>
        <li>
          <%= link_to preferences_path do %>
            <i class="fa fa-cog"></i><%= t(".preferences", default: "Preferences") %>
          <% end %>
        </li>
        <li>
          <%= link_to favorites_path do %>
            <i class="fas fa-heart"></i>My favorites</a>
          <% end %>
        </li>
        <li>
          <%= link_to donations_path do %>
            <i class="fas fa-history"></i>My donations</a>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i><%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
  <!-- Login link (when logged out) -->
      <div>
        <div class="user-container">
          <h2>Sign in</h2>
        </div>
      <%= render 'devise/sessions/new' %>
    </div>

  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% if action_name == 'edit' || controller_name != 'registrations' && controller_name != 'sessions' %>
  <div class="navbar-agapay">
      <div onclick="toggleMenu(event, this)">
        <%=  image_tag "bars.svg", height: '25', width: '25' %>
      </div>
      <%= render 'shared/menu' %>
      <div>
        <%= link_to "AGAPAY", charities_path, class: "navbar-brand"%>
      </div>
    <!-- Search -->
    <div class="navbar-form">
      <% if action_name == 'index' && controller_name == 'charities' %>
        <%= render 'shared/search_form'  %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="navbar-agapay logo-centered">

    <div>
      <%= link_to "AGAPAY", charities_path, class: "navbar-brand"%>
    </div>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<div class="search-bar">
  <div class="search-button" onclick="toggleSearchbar(event, this)">
    <button class="submit">
      <%=  image_tag("search_icon.svg", height: '23', width: '23', class: 'search_button fa fa-search search_icon', alt: 'Find') %>
    </button>
  </div>
  <div id="search-bloc">
    <div class="search-wrapper">
      <%= form_tag search_path, remote: :true, method: :get, id: "the-basics", class: "search" do |f| %>
        <div id="charity-names" data-names="<%= @charities.pluck(:name).flatten.uniq.to_json %>"></div>
        <div id="cities-names" data-names="<%= @charities.pluck(:city).flatten.uniq.to_json %>"></div>
        <div id="provinces-names" data-names="<%= @charities.pluck(:province).flatten.uniq.to_json %>"></div>
        <div id="categories-names" data-names="<%= @charities.map(&:categories).flatten.map(&:name).uniq.to_json%>"></div>


        <div class="search-filter-bar">
          <div class="button-submit">
            <button class="submit">
              <%=  image_submit_tag("search_icon.svg", height: 20, class: 'search_button fa fa-search search_icon', alt: 'Find') %>
            </button>
          </div>
          <%= text_field_tag :query, params[:query], class: "typeahead search_field",placeholder: "Search" %>
          <div class="form-group filter">
            <% @categories.each do |category| %>
              <input type="checkbox" name="categories[<%= category.id %>]" id="charity_category_names_<%= category.name %>" class="hidden" >
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div id="filters-button" onclick="toggleSidebar(event, this)">
      <%=  image_tag "filter.svg", height: 20 %>
    </div>

    <div id="filters-close" onclick="toggleSearchbar(event, this)">
      <%= image_tag "close.svg", class: 'icon_close', height: '20', width: '20' %>
    </div>
  </div>
</div>