config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  resources :charities, only: [:index, :show] do
    resources :payments, only: [:new, :create]
    post "favorite", to: "charities#favorite", as: :favorite
    post "dislike", to: "charities#dislike", as: :dislike
    resources :donations, only: [:new ]
  end
  resources :bookmarks, only: [:update, :destroy]
  resources :donations, only: [ :index ]
  resources :user_categories, only: [:update]

  get '/preferences', to: 'categories#index', as: :preferences
  get '/search', to: 'charities#search', as: 'search'
  get '/favorites', to: 'charities#user_charities_index', as: :favorites
end

app/models/charity.rb
class Charity < ApplicationRecord
  include PgSearch
  has_many :charity_categories, dependent: :destroy
  has_many :categories, through: :charity_categories
  has_many :user, through: :user_charities
  has_many :user_charities, dependent: :destroy
  has_many :pictures, dependent: :destroy
  validates :city, presence: :true
  validates :province, presence: :true
  validates :business_number, presence: :true
  validates :name, presence: true, uniqueness: true


  pg_search_scope :global_search,
  against: [ :name, :city, :province ],
  associated_against: {
    categories: [ :name ]
  },
  using: {
    tsearch: { prefix: true }
  }
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  def liked(current_user)
    favorite = UserCharity.where(user: current_user, charity: self)
    favorite.empty? ? false : true
  end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
 before_action :authenticate_user!, only: [:favorite]

  def index
    @donation = Donation.new()
    if current_user && current_user.categories.any?
      # @categories_user = current_user.categories
      # charities_user = []
      # @categories_user.each do |category|
      #   charities_user << category.charities
      # end
      # @charities = charities_user.flatten.uniq
      categories_user_ids = current_user.categories.pluck(:id)
      charity_ids = CharityCategory.where(category_id: categories_user_ids).pluck(:charity_id)
      exclude_charity_ids = UserCharity.where(user: current_user, disliked: true).pluck(:charity_id)

      charity_ids = charity_ids - exclude_charity_ids

      @charities = Charity.includes(:user_charities, :categories).where(id: charity_ids)

    elsif current_user
      charity_ids = UserCharity.where(user: current_user, disliked: true).pluck(:charity_id)
      @charities = Charity.includes(:user_charities, :categories).where.not(id: charity_ids)
    else
       @charities = Charity.includes(:user_charities, :categories).all
    end

    @categories = Category.where('name != ? AND name != ?', 'public-benefit', 'religion')

  end


   def search
    @donation = Donation.new()

    if params[:query].present?
      @charities = Charity.global_search("%#{params[:query]}%")
    else
      @charities = Charity.all
    end

    if params[:categories].present?
      category_ids = params[:categories].keys
      charity_ids = @charities.pluck(:id)

      @charities = Charity.joins(:charity_categories).where(
        charity_categories: {
          category_id: category_ids
        },
        id: charity_ids
      ).uniq
    end
  end

  def show
    @donation = Donation.new
    @charity = Charity.find(params[:id])
    @markers = [{
      lat: @charity.latitude,
      lng: @charity.longitude,
    }]
  end

  def dislike
    @charity = Charity.find(charity_params[:charity_id])
    @disliked = UserCharity.where(user: current_user, charity: @charity)

    if @disliked.empty?
      @disliked = UserCharity.create(user: current_user, charity: @charity, disliked: true)
    else
      @disliked.update(disliked: true)
    end

  end

  def favorite
    @prev = Rails.application.routes.recognize_path(request.referrer)[:action]
    @charity = Charity.find(charity_params[:charity_id])

    @favorite = UserCharity.where(user: current_user, charity: @charity)

    if @favorite.empty?
      @favorite = UserCharity.create(user: current_user, charity: @charity)
    else
      @favorite.first.destroy
    end
  end

  def user_charities_index
    current_user.user_charities.pluck()
    @favorites = Charity.joins(:user_charities).where(user_charities: {user_id: current_user.id, disliked: false})

    @donation = Donation.new
  end


  private

  def charity_params
    params.permit(:charity_id)
  end
end

app/views/charities/_charity_card.html.erb
<div id="charity-card-<%= charity.id %>" class="col-xs-12 col-sm-6 col-md-4 card-wrapper">
  <%= link_to charity_path(charity) do %>
    <div class="card" >
      <div class="card-photo">
        <%= image_tag "#{charity.logo}" %>
      </div>
      <div class="card-category-index">
        <% charity.categories.each do |cat|   %>
          <% if cat.name == "arts-culture"  %>
            <div class="tag-<%= cat.name %> tags">Arts & Culture</div>
          <% elsif cat.name == "indigenous-peoples"  %>
            <div class="tag-<%= cat.name %> tags">Indigenous Peoples</div>
          <% elsif cat.name == "social-services"  %>
            <div class="tag-<%= cat.name %> tags">Social Services</div>
          <% else %>
            <div class="tag-<%= cat.name %> tags"><%= cat.name.capitalize %></div>
          <% end %>
        <% end %>
      </div>
      <div class="card-content">
        <h2>
          <%= charity.name.upcase %>
        </h2>
        <div class="only-p-tags"><%= sanitize(charity.description.truncate_words(25, separator: /\s/, escape: false)) %></div>
      </div>
      <div class="card-hover">
      </div>
    </div>
  <% end %>
  <div class="card-favorite">
    <div id="fav-<%= charity.id %>" class="<%= charity.liked(current_user) ? 'liked' : '' %>">
      <%= link_to charity_favorite_path(charity), method: :post, remote: :true do  %>
          <%= inline_svg('empty_heart')%>
      <% end %>
    </div>
  </div>
  <div class="card-buttons">
    <%= link_to "#", class: "sweet-alert-demo", "data-id" => charity.id do  %>
      <%= image_tag "no.svg" %>
    <% end %>
    <%= link_to("#", { class: "donatecard-button", "data-toggle" => "modal", "data-target" => "#charity-modal-#{charity.id}" }) do %>
     <%= image_tag "donate.svg" %>
    <% end %>
  </div>
</div>


<%= render 'charities/donation_form', charity: charity %>

app/views/charities/_donation_form.html.erb
<div class="modal fade bd-example-modal-lg text-center" id="charity-modal-<%= charity.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-content">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 form-login">
      <div class="menu-signin">
        <div class="card-photo">
          <%= image_tag "#{charity.logo}" %>
        </div>
        <h2><%= charity.name %></h2>
        <h4>How much would you like to give?</h4>
        <%= simple_form_for @donation, url: charity_payments_path(charity), html: { id: "donation-form-#{charity.id}" } do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token, id: "charity-auth-token-#{charity.id}" %>
          <%= f.input(:donation_amount, { label: false, as: :slider, min: 0, max: 100, input_html: { id: "donation-amount-#{charity.id}"}}) %>
          <%= hidden_field_tag "stripe_token", nil, id: "stipe-token-#{charity.id}" %>
          <div>
            <button class="modal-button" id="donate-button-<%= charity.id %>">Donate</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
   <% if user_signed_in? %>
    document.getElementById("donate-button-<%= charity.id %>").addEventListener("click", function(event) {
      StripeCheckout.configure({
        // source: "slksm;lkbms;lbkms;blks",
        key: "<%= Rails.configuration.stripe[:publishable_key] %>",
        token: function(token) {
          document.getElementById("stipe-token-<%= charity.id %>").value = token.id;
          document.getElementById("donation-form-<%= charity.id %>").submit();
        }
      }).open({
        amount: parseInt(document.getElementById("donation-amount-<%= charity.id %>").value) * 100,
        name: "Donate",
        email: "<%= current_user.email %>"
      });

      event.preventDefault();
    });
    <% end %>
  </script>
<% end %>

app/views/charities/dislike.js.erb
document.getElementById("charity-card-<%= @charity.id %>").remove();

app/views/charities/favorite.js.erb
document.getElementById("fav-<%= @charity.id %>").classList.toggle("liked");

<% if @prev == "user_charities_index" %>
  document.getElementById("charity-card-<%= @charity.id %>").remove();
<% end %>

app/views/charities/index.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>

<div class="container">
  <div class="row cards-all">
    <div id="charities">
      <% @charities.each do |charity| %>
        <%= render "charities/charity_card", charity: charity %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/filters" %>

app/views/charities/search.js.erb
  function addCharity(charityHTML) {
  var charities = document.getElementById('charities');
  charities.insertAdjacentHTML('beforeend', charityHTML);
}

document.getElementById('charities').innerHTML = "";

<% @charities.each do |charity| %>
    addCharity('<%= j render "charities/charity_card", charity: charity %>');
    var slider = new Slider('#donation-amount-<%= charity.id %>', {
    formatter: function(value) {
      return 'Current value: ' + value;
    }
  });

  <% if user_signed_in? %>
  document.getElementById("donate-button-<%= charity.id %>").addEventListener("click", function(event) {
      StripeCheckout.configure({
        // source: "slksm;lkbms;lbkms;blks",
        key: "<%= Rails.configuration.stripe[:publishable_key] %>",
        token: function(token) {
          document.getElementById("stipe-token-<%= charity.id %>").value = token.id;
          document.getElementById("donation-form-<%= charity.id %>").submit();
        }
      }).open({
        amount: parseInt(document.getElementById("donation-amount-<%= charity.id %>").value) * 100,
        name: "Donate",
        email: "<%= current_user.email %>"
      });

      event.preventDefault();
    });
  <% end %>
<% end %>

app/views/charities/show.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<% content_for :meta_title, "#{@charity.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @charity.description %>
<% content_for :meta_image, @charity.logo %>

<div class="img_show">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @charity.pictures.each_with_index do |picture, index| %>
        <li data-target="#myCarousel" data-slide-to="<%= index.to_s %>" class="<%= index == 0 ? 'active' : '' %>"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% @charity.pictures.each_with_index do |picture, index| %>
        <div class="item <%= index == 0 ? 'active' : '' %>">
          <% if picture.image_url =~ /youtube/ %>
            <iframe style="height: 60vh; width: 100vw" src="https://www.youtube.com/embed/<%= @charity.pictures.first.image_url.split("/")[-1] %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          <% else %>
            <img src="<%= picture.image_url %>" alt="<%= picture.id %>" style="height: 60vh; width: auto; object-fit: cover;">
          <% end %>
        </div>
      <% end %>
    </div>

    <a class="carousel-control left-smooth" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control right-smooth" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>
<div class="wrapper">
  <div class="content-wrapper">
    <% if current_user %>
      <div class="flex-show">
        <div class="show-back">
          <a href="javascript:history.back()" class="back-button"><i class="fas fa-arrow-left"></i>Back</a>
        </div>
        <div class="card-favorite-show">
          <div id="fav-<%= @charity.id %>" class="<%= @charity.liked(current_user) ? 'liked' : '' %>">
            <%= link_to charity_favorite_path(@charity), method: :post, remote: :true, class: 'heart-show' do  %>
                <%= inline_svg('empty_heart')%>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="show-back">
        <a href="javascript:history.back()" class="back-button"><i class="fas fa-arrow-left"></i>Back</a>
      </div>
    <% end %>
    <div class="show-category">
      <% @charity.categories.each do |cat|   %>
        <% if cat.name == "arts-culture"  %>
          <div class="tag-<%= cat.name %> tags">Arts & Culture</div>
        <% elsif cat.name == "indigenous-peoples"  %>
          <div class="tag-<%= cat.name %> tags">Indigenous Peoples</div>
        <% elsif cat.name == "social-services"  %>
          <div class="tag-<%= cat.name %> tags">Social Services</div>
        <% else %>
          <div class="tag-<%= cat.name %> tags"><%= cat.name.capitalize %></div>
        <% end %>
      <% end %>
    </div>

    <div class="show-content">
      <% charityc = @charity.name.split(" ") do |elem| elem.upcase end %>
        <h2><%= charityc.join(" ") %></h2>
      <%= sanitize @charity.description %>
    </div>
    <%= link_to( "#", { style: 'width: 70px;', class: "button-donate-phone", "data-toggle" => "modal", "data-target" => "#charity-modal-#{@charity.id}" } ) do %>
      <%= image_tag "donate.svg" %>
    <% end %>
    <div class="flex-donate hidden-xs">
      <%= link_to("Donate", "#", { class: "btn btn-success button-donate-desktop", "data-toggle" => "modal", "data-target" => "#charity-modal-#{@charity.id}" } ) %>
    </div>
  </div>
    <div class="mapshow" id="map" data-markers="<%= @markers.to_json %>">
  </div>
</div>

<%= render 'charities/donation_form', charity: @charity %>

app/views/charities/user_charities_index.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>

<div class="container">
  <div class="row">
    <div id="charities">
      <% if @favorites.any? %>
        <% @favorites.each do |charity| %>
          <%= render "charities/charity_card", charity: charity %>
        <% end %>
      <% else %>
        <div class="list-empty">
          <h3>No bookmarked charities.</h3>
          <%= link_to 'Find your own!', charities_path, class: "btn btn-signin" %>
        </div>
      <% end %>
    </div>
  </div>
</div>