config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  resources :charities, only: [:index, :show] do
    resources :payments, only: [:new, :create]
    post "favorite", to: "charities#favorite", as: :favorite
    post "dislike", to: "charities#dislike", as: :dislike
    resources :donations, only: [:new ]
  end
  resources :bookmarks, only: [:update, :destroy]
  resources :donations, only: [ :index ]
  resources :user_categories, only: [:update]

  get '/preferences', to: 'categories#index', as: :preferences
  get '/search', to: 'charities#search', as: 'search'
  get '/favorites', to: 'charities#user_charities_index', as: :favorites
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # before_action :set_donation, only: [:create]
 before_action :authenticate_user!, only: [:create]

  def new
  end

  def create

    charity = Charity.find(params[:charity_id])
    donation_amount = params[:donation][:donation_amount]

    customer = Stripe::Customer.create(
      source: params[:stripe_token],
      email:  current_user.email
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       donation_amount.to_i * 100,
      description:  "Donation of #{donation_amount} to #{charity.name}",
      currency:     "CAD"
    )

    if charge.failure_code == nil && charge.status == "succeeded"
      donation = Donation.create!({
        donation_amount: donation_amount.to_i,
        user: current_user,
        state: 'accepted', # FIXME Remove
        charity: charity,

      })
      flash[:notice] = "Thank you for your payment"
      # redirect_to donations_path
    else
      flash[:alert] = "Payment didn't go through"# flash a messages
    end

    redirect_to charities_path
  end

private

  def set_donation
    @donation = current_user.donations.where(state: 'pending').find(params[:donation_id])
  end
end

app/views/payments/new.html.erb
<h1>Purchase of teddy <%= @donation.teddy_sku %></h1>
<%= form_tag donation_payments_path(@donation) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@donation.donation_amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Charity"
    data-email="<%= current_user.email %>"
    data-description="Charity <%= @donation.id %>"
    data-amount="<%= @donation.donation_amount_cents %>"
    data-currency="<%= @donation.donation_amount.currency %>"></script>
<% end %>