config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  resources :charities, only: [:index, :show] do
    resources :payments, only: [:new, :create]
    post "favorite", to: "charities#favorite", as: :favorite
    post "dislike", to: "charities#dislike", as: :dislike
    resources :donations, only: [:new ]
  end
  resources :bookmarks, only: [:update, :destroy]
  resources :donations, only: [ :index ]
  resources :user_categories, only: [:update]

  get '/preferences', to: 'categories#index', as: :preferences
  get '/search', to: 'charities#search', as: 'search'
  get '/favorites', to: 'charities#user_charities_index', as: :favorites
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :charity_categories
  has_many :charities, through: :charity_categories

  CATEGORY_PRETTY_NAME_LOOKUP = {
    "environment" => "Environment",
    "international" => "International",
    "health" => "Health",
    "arts-culture" => "Art & Culture",
    "animals" => "Animals",
    "education" => "Education",
    "social-services" => "Social Services",
    "indigenous-peoples" => "Indigenous Peoples"
  }

  def pretty_name
    CATEGORY_PRETTY_NAME_LOOKUP[self.name]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where.not(name: ["public-benefit", "religion"])
  end
end

app/views/categories/index.html.erb
<div class="container">
  <div class="row preferences-bloc">
    <div class="col-xs-12">
      <% @categories.each do |category| %>
        <%= link_to user_category_path(category), method: :patch, class: 'link-text-pref', remote: :true do %>
          <div class="col-xs-6 col-s-3 col-md-3 card-category">
            <div class="focus-box preference-box <%= 'focs' if current_user.has_category_as_preference(category) %> <%= category.name %>">
              <div class="category-info">
                <%= image_tag category.name, size: "49x25" %>
                <p style="margin-top: 8px;"><%= category.pretty_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="text-center">
        <%= link_to 'Save', charities_path, class: "btn btn-success category-button", style: "margin: 30px auto; width: 100%;"%>
      </div>
    </div>
  </div>
</div>